[project]
name = "givenergy-cli"
version = "0.1.0"
description = "Command-line interface to control GivEnergy systems via the local network"
readme = "README.md"
license = "Apache-2.0"
authors = [{ name = "Dewet Diener", email = "givenergy-modbus@dewet.org" }]
requires-python = ">=3.14,<4.0"
dependencies = [
    "givenergy-modbus>=2.1.0b4,<3.0.0",
    "typer>=0.25.1,<0.26.0",
    "textual>=8.2.5,<9.0.0",
]

[project.scripts]
givenergy-cli = "givenergy_cli.__main__:app"

[dependency-groups]
dev = [
    "pytest>=9.0.0,<10.0.0",
    "ruff>=0.15.12,<0.16.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["givenergy_cli"]
